// بيانات المطاعم والمحلات النموذجية لموقع دليل مغاغة للمطاعم
export const CATEGORIES = [
  { id: "all", name: "الكل", icon: "fa-store" },
  { id: "grill", name: "المشويات", icon: "fa-fire-burner" },
  { id: "syrian", name: "سوري/شاورما", icon: "fa-fire" },
  { id: "crepe", name: "كريب/بيتزا", icon: "fa-pizza-slice" },
  { id: "sweets", name: "وافل/حلويات", icon: "fa-ice-cream" },
  { id: "chicken", name: "فرايد تشكن /بروست", icon: "fa-drumstick-bite" },
  { id: "burger", name: "سماش برجر", icon: "fa-burger" },
  { id: "koshary", name: "كشري", icon: "fa-bowl-food" },
  { id: "fish", name: "الأسماك", icon: "fa-fish" },
];

export const RESTAURANTS = [
  {
    id: 21,
    name: "مطعم توكيو - Tokyo",
    category: "crepe",
    logo: "tokyo-logo",
    description:
      "مطعم توكيو لجميع أنواع الكريب الإيطالي المميز والبيتزا الغنية بأجود المكونات في مغاغة.",
    phones: ["01221104263"],
    whatsApp: "",
    deliveryFee: "من 20 لـ 30 جنيه",
    address: "مغاغة - شارع السلام - امام هارد روك",
    workingHours: {
      start: "12:00",
      end: "02:00",
      display: "من 12:00 ظهراً إلى 2:00 بعد منتصف الليل",
    },
    popularItems: [
      {
        name: "كريب نوتيلا بالموز",
        price: 65,
        description: "كريب نوتيلا غني مع الموز الطازج والمكسرات",
      },
      {
        name: "بيتزا تشيكن رانش وسط",
        price: 110,
        description:
          "بيتزا وسط مغطاة بقطع الدجاج، صوص الرانش اللذيذ، فلفل ألوان، وموزاريلا",
      },
    ],
    menuImages: [
      "tokyo-menu1",
      "tokyo-menu2",
      "tokyo-menu3",
      "tokyo-menu4",
      "tokyo-menu5",
    ],
  },
  {
    id: 23,
    name: "اسماك يونس",
    category: "fish",
    logo: "youns-logo",
    description:
      "اسماك يونس لجميع المأكولات البحرية الطازجة، صواني فرن، طواجن، وألذ الوجبات في مغاغة.",
    phones: ["01203504063", "01111475437", "01040092445"], // Using valid call phones
    whatsApp: "201113826695",
    deliveryFee: "من 20 لـ 30 جنيه",
    address: "ش الثورة - امام كشري هند",
    workingHours: {
      start: "12:00",
      end: "02:00",
      display: "من 12:00 ظهراً إلى 2:00 بعد منتصف الليل",
    },
    popularItems: [
      {
        name: "كيلو سمك بلطي مشوي",
        price: 120,
        description: "سمك بلطي طازج متبل ومشوي بالردة على اللهب",
      },
      {
        name: "طاجن فواكه البحر بالكريمة وسط",
        price: 160,
        description:
          "تشكيلة جمبري، كاليماري، فيليه بخلطة الكريمة والجبنة في الفرن",
      },
    ],
    menuImages: ["youns-menu1", "youns-menu2"],
  },
  {
    id: 22,
    name: "تيك اوي حوده",
    category: "crepe",
    logo: "houda-logo",
    description:
      "تيك اوي حوده يقدم أشهى وأفضل أنواع الكريب والبيتزا الإيطالية والسندوتشات الغربية اللذيذة في مغاغة.",
    phones: ["01025850812"],
    whatsApp: "",
    deliveryFee: "من 20 لـ 30 جنيه",
    address: "مغاغة - شارع الثورة - بجوار حلا بحليب",
    workingHours: {
      start: "12:00",
      end: "02:00",
      display: "من 12:00 ظهراً إلى 2:00 بعد منتصف الليل",
    },
    popularItems: [
      {
        name: "كريب كرانشي سوبريم",
        price: 75,
        description:
          "كريب مقرمش غني بقطع الفرايد تشكن، البطاطس، الموتزاريلا والصوصات",
      },
      {
        name: "بيتزا مارجريتا وسط",
        price: 70,
        description:
          "عجينة بيتزا إيطالية مميزة بصلصة الطماطم الغنية والجبن الموزاريلا",
      },
    ],
    menuImages: ["houda-menu1", "houda-menu2", "houda-menu3"],
  },
  {
    id: 20,
    name: "جدو الشام - Gedo Elsham",
    category: "syrian",
    logo: "gedo-logo",
    description:
      "أفضل شاورما سوري، فتة، ساندوتشات غربية، وأكلات شامية لذيذة في مغاغة.",
    phones: ["01002405348"],
    whatsApp: "",
    deliveryFee: "من 20 لـ 30 جنيه",
    address: "مغاغة - شارع الشعبة (أمام بن الأسمر)",
    workingHours: {
      start: "12:00",
      end: "02:00",
      display: "من 12:00 ظهراً إلى 2:00 بعد منتصف الليل",
    },
    popularItems: [
      {
        name: "ساندوتش شاورما دجاج سوبر عربي",
        price: 80,
        description:
          "شاورما دجاج، تومية، مخلل، خبز صاج مقرمش مع بطاطس فارم فريتس",
      },
      {
        name: "فتة شاورما دجاج وسط",
        price: 95,
        description:
          "أرز بسمتي مبهر، شاورما دجاج، خبز محمص، وصوص التومية الغني",
      },
      {
        name: "وجبة نصف دجاجة بروستد",
        price: 135,
        description:
          "2 قطعة دجاج بروستد مقرمش، بطاطس، تومية، كول سلو، خبز سوري",
      },
    ],
    menuImages: ["gedo-menu1", "gedo-menu2"],
  },
  {
    id: 19,
    name: "كشري هند - Koshary Hend",
    category: "koshary",
    logo: "hind-logo",
    description:
      "أشهر وألذ أطباق الكشري المصري الأصيل والطواجن المتنوعة في مغاغة بفرعيه.",
    phones: ["01210195153", "01015061338"],
    secondBranchPhones: ["01206500071", "01116816266"],
    whatsApp: "",
    deliveryFee: "من 20 لـ 30 جنيه",
    address: "مغاغة - فرع شارع الثورة (أمام أسواق سيف) | فرع شارع المحطة",
    workingHours: {
      start: "12:00",
      end: "02:00",
      display: "من 12:00 ظهراً إلى 2:00 بعد منتصف الليل",
    },
    popularItems: [
      {
        name: "علبة كشري هند خصوصي",
        price: 40,
        description:
          "أرز، مكرونة، عدس، حمص، بصل مقرمش مع الصلصة والتقلية المميزة",
      },
      {
        name: "طاجن لحمة مفرومة بالفرن",
        price: 55,
        description: "مكرونة فرن باللحمة المفرومة والصلصة الحمراء الغنية",
      },
      {
        name: "طاجن فراخ بالجبنة الموتزاريلا",
        price: 65,
        description:
          "مكرونة بقطع الدجاج والصلصة مغطاة بطبقة غنية من الموزاريلا",
      },
    ],
    menuImages: ["hind-menu1", "hind-menu2", "hind-menu3", "hind-menu4"],
  },
  {
    id: 18,
    name: "هاي بروست - Hy Broasted",
    category: "chicken",
    logo: "hy-brosted-logo",
    description:
      "أقوى بروست مقرمش ووجبات فرايد تشيكن غنية بخلطات وتتبيلات هاي المميزة في مغاغة.",
    phones: ["01287877563", "01110771334", "01020020965"],
    whatsApp: "",
    deliveryFee: "من 20 لـ 30 جنيه",
    address: "مغاغة - شارع الشعبة / الزهور، متفرع من شارع السلام",
    workingHours: {
      start: "12:00",
      end: "02:00",
      display: "من 12:00 ظهراً إلى 2:00 بعد منتصف الليل",
    },
    popularItems: [
      {
        name: "وجبة سوبر هاي بروست (4 قطع)",
        price: 145,
        description:
          "4 قطعة دجاج بروست مقرمش، بطاطس فارم فريتس، تومية، كول سلو، خبز",
      },
      {
        name: "وجبة العيلة هاي (8 قطع)",
        price: 270,
        description:
          "8 قطع بروست مقرمش، بطاطس عائلية، لتر كولا، كول سلو كبير وخبز",
      },
      {
        name: "ساندوتش تشيكن رويال العملاق",
        price: 90,
        description:
          "صدور دجاج كريسبي، جبنة شيدر سايحة، خس، خيار مخلل وصوص هاي السري",
      },
    ],
    menuImages: ["hy-brosted-menu1", "hy-brosted-menu2"],
  },
  {
    id: 17,
    name: "مطعم عروس الشام - Arous El Sham",
    category: "syrian",
    logo: "arous-alsham-logo",
    description:
      "أشهى المأكولات السورية، الشاورما، الفتات، والوجبات المتنوعة بطعم الشام الأصيل في مغاغة.",
    phones: ["01031115114", "01128904090"],
    whatsApp: "",
    deliveryFee: "من 20 لـ 30 جنيه",
    address: "مغاغة - شارع السلام، ميدان الحمامة",
    workingHours: {
      start: "12:00",
      end: "02:00",
      display: "من 12:00 ظهراً إلى 2:00 بعد منتصف الليل",
    },
    popularItems: [
      {
        name: "🎁 عرض عروس الشام الخاص",
        price: "حسب الاختيار",
        description:
          "اشتري 2 كريب من اختيارك وخد عليهم ساندوتش شاورما كبير هدية مجاناً! 🔥",
      },
      {
        name: "ماريا شاورما دجاج سبيشال",
        price: 85,
        description:
          "خبز صاج محشو شاورما دجاج، جبنة موزاريلا، تومية ومخلل مشوي على الجريل",
      },
      {
        name: "فتة شاورما مشكل (دبل)",
        price: 110,
        description:
          "أرز بسمتي مبهر، شاورما لحم ودجاج، خبز مقرمش وصوص تومية مميز",
      },
      {
        name: "وجبة عربي سوبر دجاج",
        price: 95,
        description:
          "قطع رول شاورما مقطعة تقدم مع بطاطس فارم فريتس، تومية، مخلل وكول سلو",
      },
    ],
    menuImages: ["arous-alsham-menu1", "arous-alsham-menu2"],
  },
  {
    id: 16,
    name: "بابا برجر - Baba Burger",
    category: "burger",
    logo: "baba-food-logo",
    description:
      "أفضل وأجود ساندوتشات السماش برجر اللحم والدجاج الطازج بخلطتنا الفريدة في مغاغة.",
    phones: ["01118487387"],
    whatsApp: "201118487387",
    deliveryFee: "من 20 لـ 30 جنيه",
    address: "مغاغة - شارع الثورة، بجوار حلو الشام",
    workingHours: {
      start: "12:00",
      end: "02:00",
      display: "من 12:00 ظهراً إلى 2:00 بعد منتصف الليل",
    },
    popularItems: [
      {
        name: "سماش برجر كلاسيك (سنجل)",
        price: 70,
        description:
          "قطعة لحم سماش، جبنة شيدر، خس، طماطم، خيار مخلل، صوص بابا المميز",
      },
      {
        name: "بابا برجر دبل سماش",
        price: 95,
        description: "قطعتين لحم سماش، دبل جبنة شيدر، بصل مكرمل وصوص خاص",
      },
      {
        name: "ساندوتش دجاج كريسبي بابا",
        price: 80,
        description: "صدر دجاج مقرمش، جبنة شيدر سايحة، خس، مايونيز",
      },
    ],
    menuImages: ["baba-food-menu"],
  },
  {
    id: 11,
    name: "مزيكا كريب - Mazeka Crepe",
    category: "crepe",
    logo: "mazeka-logo",
    description: "أطعم وأكبر كريب حادق وحلو وبيتزا إيطالي مميزة في مغاغة.",
    phones: ["01024716334", "01110672280"],
    whatsApp: "",
    deliveryFee: "من 20 لـ 30 جنيه",
    address: "مغاغة - شارع الثورة - أمام مطعم زيزو",
    workingHours: {
      start: "12:00",
      end: "02:00",
      display: "من 12:00 ظهراً إلى 2:00 بعد منتصف الليل",
    },
    popularItems: [
      {
        name: "كريب سوبر كرانشي حار",
        price: 75,
        description: "فرايد تشيكن مقرمش، بطاطس، جبن موزاريلا، صوصات مميزة",
      },
      {
        name: "كريب بطاطس سوري بالجبنة",
        price: 40,
        description: "بطاطس مقلية مع تشكيلة جبن وصوص تومية",
      },
      {
        name: "بيتزا سوبر سوبريم وسط",
        price: 95,
        description: "شرائح لحوم متبلة، موزاريلا، خضروات طازجة",
      },
    ],
    menuImages: ["mazeka--meanu"],
  },
  {
    id: 12,
    name: "مطعم الثورة - El Thawra Restaurant",
    category: "crepe",
    logo: "elthwra-menu",
    description: "أشهى كريب وسندوتشات غربية متنوعة وبيتزا إيطالية مميزة.",
    phones: ["01128804535", "01032527269"],
    whatsApp: "",
    deliveryFee: "من 20 لـ 30 جنيه",
    address: "مغاغة - شارع الثورة، بجوار قصر السلطان",
    workingHours: {
      start: "12:00",
      end: "02:00",
      display: "من 12:00 ظهراً إلى 2:00 بعد منتصف الليل",
    },
    popularItems: [
      {
        name: "كريب زنجر سوبريم حار",
        price: 80,
        description: "قطع زنجر الدجاج الحار، جبن موزاريلا، فلفل، زيتون، صوصات",
      },
      {
        name: "بيتزا مارجريتا (وسط)",
        price: 65,
        description:
          "عجينة بيتزا إيطالية غنية بالجبن الموزاريلا وصلصة الطماطم المتبلة",
      },
      {
        name: "كريب شاورما دجاج جامبو",
        price: 75,
        description: "شاورما دجاج، جبن شيدر وموزاريلا، بطاطس، تومية وصوصات",
      },
    ],
    menuImages: ["elthwra"],
  },
  {
    id: 14,
    name: "كريب وبيتزا الشريعي - El Shraea Crepe & Pizza",
    category: "crepe",
    logo: "elshraea-logo",
    description:
      "أجود أنواع الكريب والبيتزا الإيطالية والسندوتشات الغربية اللذيذة.",
    phones: ["01201882717"],
    whatsApp: "",
    deliveryFee: "من 20 لـ 30 جنيه",
    address: "مغاغة - شارع السلام، أمام مدرسة الراهبات",
    workingHours: {
      start: "12:00",
      end: "02:00",
      display: "من 12:00 ظهراً إلى 2:00 بعد منتصف الليل",
    },
    popularItems: [
      {
        name: "كريب زنجر سوبر سوبريم",
        price: 75,
        description:
          "قطع زنجر الدجاج، بطاطس، موزاريلا، كاتشب، مايونيز، زيتون، فلفل",
      },
      {
        name: "بيتزا تشيكن رانش وسط",
        price: 90,
        description: "صدور دجاج، صوص رانش، موزاريلا، فلفل، زيتون",
      },
      {
        name: "كريب نوتيلا بالموز والمكسرات",
        price: 50,
        description: "كريب حلو غني بالنوتيلا والموز والمكسرات",
      },
    ],
    menuImages: ["elshraea2-menu1", "elshraea2-menu2"],
  },
  {
    id: 8,
    name: "مشويات أبو طلعت - Abo Talaat Grill",
    category: "grill",
    logo: "abo-talaat-logo",
    description:
      "أفضل الكباب والكفتة والمشويات على الفحم بطعم مغاغي بلدي أصيل.",
    phones: ["01113567679", "01023449972"],
    whatsApp: "",
    deliveryFee: "من 20 لـ 30 جنيه",
    address: "مغاغة - شارع السلام - بجوار مسجد السمسطاوي",
    workingHours: {
      start: "12:00",
      end: "02:00",
      display: "من 12:00 ظهراً إلى 2:00 بعد منتصف الليل",
    },
    popularItems: [
      {
        name: "كيلو كفتة مشوية على الفحم",
        price: 390,
        description: "لحم بلدي متبل على الطريقة الشرقية الأصيلة",
      },
      {
        name: "وجبة ربع كباب وكفتة",
        price: 130,
        description: "كفتة وكباب مشوي مع أرز، سلطة خضراء، طحينة، وخبز",
      },
      {
        name: "فرخة مشوية على الفحم",
        price: 240,
        description: "تقدم مع الأرز والسلطات والعيش",
      },
    ],
    menuImages: ["abo-talaat-meanu1", "abo-talaat-meanu2"],
  },
  {
    id: 7,
    name: "أبو علي بروست - Abo Ali Broast",
    category: "chicken",
    logo: "abo-ali-brost",
    description:
      "أقوى بروست مقرمش ووجبات فرايد تشكن بخلطة أبو علي السرية المميزة.",
    phones: [
      "01035890038",
      "01240077763",
      "01144074480",
      "01233370023",
      "01035872002",
      "01100896009",
    ],
    whatsApp: "",
    deliveryFee: "من 20 لـ 30 جنيه",
    address: "مغاغة - شارع الثورة - بجوار مسجد السلام",
    workingHours: {
      start: "12:00",
      end: "02:00",
      display: "من 12:00 ظهراً إلى 2:00 بعد منتصف الليل",
    },
    popularItems: [
      {
        name: "العرض الأول | لَمّة محبي الفرايد تشيكن",
        price: 149,
        description: "2 قطعة فرايد تشيكن + 2 كرسبي استربس + 2 خبز + كاتشب 🔥",
      },
      {
        name: "👑 العرض الثاني | صينية اللتاتة",
        price: 449,
        description:
          "8 قطع فرايد تشيكن + أرز بخلطة أبو علي + تومية وسط + كولسلو وسط + بطاطس بالجبنة + 4 خبز + كاتشب 😋🔥",
      },
      {
        name: "❤️ العرض الثالث | صينية الطبطبة",
        price: 399,
        description:
          "4 قطع فرايد تشيكن + 4 كرسبي استربس + أرز بالخلطة + بطاطس بالجبنة + كولسلو وسط + تومية وسط + كاتشب + 3 خبز 🍗🧀",
      },
    ],
    menuImages: ["abo-ali-meanu1", "abo-ali-meanu2"],
  },
  {
    id: 9,
    name: "دكتور بوكس - Doctor Box",
    category: "chicken",
    logo: "doctor-box",
    description:
      "وجبات تشيكن بروست وفرايد تشكن مقرمشة وساندوتشات عائلية متميزة.",
    phones: ["17818"],
    whatsApp: "",
    deliveryFee: "من 20 لـ 30 جنيه",
    address: "مغاغة – شارع السلام، أمام مدرسة الصنايع",
    workingHours: {
      start: "12:00",
      end: "02:00",
      display: "من 12:00 ظهراً إلى 2:00 بعد منتصف الليل",
    },
    popularItems: [
      {
        name: "بوكس الوجبة الفردية (3 قطع)",
        price: 110,
        description: "3 قطع دجاج بروست، بطاطس، ثومية، خبز",
      },
      {
        name: "ساندوتش دكتور تشيكن العملاق",
        price: 85,
        description: "صدور الدجاج المقرمشة بخلطة الطبيب الحارة مع الجبن السايح",
      },
      {
        name: "شيرنج بوكس العائلي (9 قطع)",
        price: 285,
        description: "9 قطع بروست، بطاطس عائلية، كول سلو كبير، خبز، لتر بيبسي",
      },
    ],
    menuImages: [
      "doctor-box-meanu1",
      "doctor-box-meanu2",
      "doctor-box-meanu3",
      "doctor-box-meanu4",
      "doctor-box-meanu5",
      "doctor-box-meanu6",
      "doctor-box-meanu7",
      "doctor-box-meanu8",
    ],
  },
  {
    id: 13,
    name: "الشريعي فرايد تشيكن - El Shraea Fried Chicken",
    category: "chicken",
    logo: "elshraea-logo",
    description:
      "أقوى وجبات الفرايد تشيكن والبروست المقرمش بعروض وخلطات مميزة.",
    phones: ["01208696419"],
    whatsApp: "",
    deliveryFee: "من 20 لـ 30 جنيه",
    address: "مغاغة - شارع السلام، أمام كوبري الصنائع",
    workingHours: {
      start: "12:00",
      end: "02:00",
      display: "من 12:00 ظهراً إلى 2:00 بعد منتصف الليل",
    },
    popularItems: [
      {
        name: "وجبة سوبر كرانشي فردية",
        price: 90,
        description: "3 قطع دجاج بروست، بطاطس، ثومية، عيش",
      },
      {
        name: "ساندوتش الشريعي العملاق",
        price: 80,
        description: "صدور دجاج كريسبي مقرمشة مع الخس والمايونيز والجبن",
      },
      {
        name: "وجبة العيلة الشريعي (12 قطعة)",
        price: 340,
        description: "12 قطعة بروست، بطاطس عائلية، كول سلو كبير، خبز ولتر كولا",
      },
    ],
    menuImages: [
      "elshraea-menu1",
      "elshraea-menu2",
      "elshraea-menu3",
      "elshraea-offer",
    ],
  },
  {
    id: 10,
    name: "كوكب السعادة - Kawkab El Saada",
    category: "sweets",
    logo: "kokap-logo",
    description:
      "أجود وأطعم أنواع الوافل، الكريب الحلو، العصائر، والحلويات المنعشة.",
    phones: ["01113914972"],
    whatsApp: "",
    deliveryFee: "من 20 لـ 30 جنيه",
    address: "مغاغة - شارع السلام، أمام الشعبة",
    workingHours: {
      start: "12:00",
      end: "02:00",
      display: "من 12:00 ظهراً إلى 2:00 بعد منتصف الليل",
    },
    popularItems: [
      {
        name: "وافل نوتيلا فواكه مشكل",
        price: 55,
        description: "وافل مغطى بالنوتيلا مع قطع الفراولة والموز والكيوي",
      },
      {
        name: "كريب حلو نوتيلا بندق",
        price: 45,
        description: "كريب رقيق محشو شوكولاتة نوتيلا وبندق محمص",
      },
      {
        name: "عصير كوكتيل كوكب السعادة",
        price: 40,
        description:
          "طبقات من المانجو والفراولة والجوافة مع قطع الفواكه الطازجة",
      },
    ],
    menuImages: ["kokap-meanu1.jpg"], // Base filename maps to kokap-meanu1.jpg.webp
  },
  {
    id: 24,
    name: "حلا بحليب - Hala B.Haleeb",
    category: "sweets",
    logo: "halabhaleeb-logo",
    description:
      "حلا بحليب لألذ وأطيب الحلويات الشرقية والغربية، الوافل، الآيس كريم، وعصائر منعشة بأعلى جودة في مغاغة.",
    phones: ["01040853091", "01228838016"],
    whatsApp: "",
    deliveryFee: "من 20 لـ 30 جنيه",
    address: "مغاغة - ش الثورة بجوار حلو الشام",
    workingHours: {
      start: "12:00",
      end: "02:00",
      display: "من 12:00 ظهراً إلى 2:00 بعد منتصف الليل",
    },
    popularItems: [
      {
        name: "طبق حلا بحليب المشكل",
        price: 65,
        description: "أرز بلبن غني مع قشطة، مكسرات، عسل وفواكه طازجة",
      },
      {
        name: "وافل نوتيلا دبل",
        price: 50,
        description:
          "وافل مقرمش مغطى بطبقة غنية من الشوكولاتة النوتيلا والمكسرات",
      },
    ],
    menuImages: ["halabhaleeb-menu1"],
  },
  {
    id: 25,
    name: "رغيف كفتة - Raghif Kofta",
    category: "grill",
    logo: "raghifkofta-logo",
    description:
      "مطعم رغيف كفتة لأشهر ساندوتشات المشويات على الفحم، كفتة، كباب، وطواجن شرقية شهية بأجود أنواع اللحوم البلدي في مغاغة.",
    phones: ["01144252519", "01095496696"],
    whatsApp: "",
    deliveryFee: "من 20 لـ 30 جنيه",
    address: "مغاغة - شارع الثورة - امام كشرى هند",
    workingHours: {
      start: "12:00",
      end: "02:00",
      display: "من 12:00 ظهراً إلى 2:00 بعد منتصف الليل",
    },
    popularItems: [
      {
        name: "ساندوتش رغيف كفتة بلدي على الفحم",
        price: 45,
        description:
          "كفتة بلدي مشوية على الفحم مع السلطات والطحينة في خبز بلدي طازج",
      },
      {
        name: "وجبة كفتة وكباب مكس",
        price: 120,
        description: "مشويات بلدي متبلة تقدم مع الأرز والعيش والسلطات",
      },
    ],
    menuImages: ["raghifkofta-menu1"],
  },

  {
    id: 27,
    name: "مطعم شطة - Shatah",
    category: "syrian",
    logo: "shatah-logo",
    description:
      "مطعم شطة لتقديم أشهى الوجبات السريعة، الكريب، وسندوتشات الشاورما السورية المميزة بمغاغة.",
    phones: ["01062049652"],
    whatsApp: "",
    deliveryFee: "من 20 لـ 30 جنيه",
    address: "مغاغة - شارع السلام",
    workingHours: {
      start: "12:00",
      end: "02:00",
      display: "من 12:00 ظهراً إلى 2:00 بعد منتصف الليل",
    },
    popularItems: [
      {
        name: "ساندوتش شاورما شطة سوبر",
        price: 85,
        description: "شاورما سوري مميزة بخبز الصاج مع الثومية والمخلل",
      },
    ],
    menuImages: ["shatah-menu1", "shatah-menu2"],
  },
  {
    id: 28,
    name: "مطعم سلوم-salom",
    category: "syrian",
    logo: "salom-logo",
    description:
      "مطعم سلوم يقدم أشهى المأكولات السورية، الشاورما، والوجبات المتنوعة بطعم مميز في مغاغة.",
    phones: ["01101025654"],
    whatsApp: "",
    deliveryFee: "من 20 لـ 30 جنيه",
    address: "مغاغة - شارع الثورة - امام ملوك النابلسية",
    workingHours: {
      start: "12:00",
      end: "02:00",
      display: "من 12:00 ظهراً إلى 2:00 بعد منتصف الليل",
    },
    popularItems: [
      {
        name: "ساندوتش شاورما سلوم سوبر عربي",
        price: 85,
        description: "شاورما سوري مميزة بخبز الصاج مع الثومية والمخلل والبطاطس",
      },
    ],
    menuImages: ["salom-menu1", "salom-menu2"],
  },
];

export const CAPTAINS = [
  {
    id: "captain_1",
    name: "الكابتن أحمد الجارحي (تجريبي)",
    avatar: "avatar-men",
    phone: "01062049652",
    serviceTypes: ["توصيل طلبات", "مشاوير"],
    isAvailable: true,
    description:
      "شاب ملتزم وموثوق، توصيل سريع وأمان كامل لطلباتكم ومأكولاتكم داخل مغاغة وضواحيها 24 ساعة.",
    tripsCount: 1,
  },
  {
    id: "captain_2",
    name: "مكتب دليفري لك",
    avatar: "dlevarlk-logo",
    phone: "01155435543",
    whatsApp: "201155435543",
    serviceTypes: ["توصيل طلبات"],
    isAvailable: true,
    description:
      "مكتب توصيل طلبات فقط، يقدم خدمة سريعة ومتميزة تشمل مدينة مغاغة بالكامل لتوصيل جميع طلباتكم.",
    tripsCount: 1,
  },
];

export const SUPERMARKETS = [
  {
    id: "supermarket_1",
    name: "هايبر العمدة - El Omda Hypermarket",
    logo: "elomda-logo",
    description:
      "سلسلة هايبر العمدة توفر جميع السلع الغذائية، المنتجات المنزلية والمستلزمات بأفضل الأسعار وخدمة دليفري لجميع مناطق مغاغة.",
    phones: ["01224161001", "01288583389", "01040092445"],
    branches: [
      "فرع 1: مغاغة العبور - شارع الثورة",
      "فرع 2: مغاغة - شارع السلام - بجوار مدرسة الراهبات",
      "فرع 3: مغاغة - منشية المصري بجوار جامع ناصر",
    ],
    deliveryFee: "خدمة توصيل فورية 🚀",
    workingHours: {
      start: "08:00",
      end: "02:00",
      display: "من 8:00 صباحاً إلى 2:00 بعد منتصف الليل",
    },
  },
  {
    id: "supermarket_2",
    name: "الوكيل لتجارة الجملة - Al Wakeel",
    logo: "alwakeel-logo",
    description:
      "محل الوكيل متخصص في بيع السلع الغذائية والبقالة الأساسية بالكامل، يقدم أسعار قطاعي بسعر الجملة لتلبية احتياجاتكم بأقل الأسعار.",
    phones: ["01015838397", "01010279704"],
    whatsApp: "201015838397",
    address: "مغاغة - شارع الزهور - بجوار شبكة المياه - خلف المطافي",
    deliveryFee: "خدمة توصيل طلبات 📦",
    workingHours: {
      start: "08:00",
      end: "02:00",
      display: "من 8:00 صباحاً إلى 2:00 بعد منتصف الليل",
    },
  },
  {
    id: "supermarket_3",
    name: "بـ جبنة - BeGebna",
    logo: "begebna-logo",
    description:
      "محل بـ جبنة لجميع أنواع الأجبان، البقالة، والمنتجات الطبيعية 100%. جميع أنواع المربات الطبيعية متاحة بجميع الأطعام المميزة في مغاغة.",
    phones: ["01156115709", "01038860273"],
    whatsApp: "201156115709",
    address: "مغاغة - شارع الثورة - خلف أسواق سيف",
    deliveryFee: "خدمة توصيل طلبات 📦",
    workingHours: {
      start: "08:00",
      end: "02:00",
      display: "من 8:00 صباحاً إلى 2:00 بعد منتصف الليل",
    },
    popularItems: [
      {
        name: "مربى توت طبيعي 100%",
        price: "حسب الحجم",
        description: "مربى توت طبيعي طازجة وبدون مواد حافظة 💛👌🏻",
      },
      {
        name: "مربى فراولة طبيعي 100%",
        price: "حسب الحجم",
        description: "مربى فراولة طازجة طبيعية 100% 💛👌🏻",
      },
      {
        name: "مربى مانجو طبيعي 100%",
        price: "حسب الحجم",
        description: "مربى مانجو طبيعية بطعم غني 💛👌🏻",
      },
      {
        name: "مربى كيوي طبيعي 100%",
        price: "حسب الحجم",
        description: "مربى كيوي طبيعي 100% 💛👌🏻",
      },
      {
        name: "مربى تين طبيعي 100%",
        price: "حسب الحجم",
        description: "مربى تين طبيعي طازجة وبدون مواد حافظة 💛👌🏻",
      },
      {
        name: "مربى مشمش طبيعي 100%",
        price: "حسب الحجم",
        description: "مربى مشمش طبيعية 100% 💛👌🏻",
      },
    ],
    menuImages: ["begebna-menu2", "begebna-menu1"],
  },
];

export const INITIAL_JOB_SEEKERS = [
  {
    id: "seeker_1",
    name: "باحث عن عمل (نموذج توضيحي 1)",
    jobDesired: "كاشير ومبيعات محلات",
    age: "23 سنة",
    education: "مؤهل عالي تجاري",
    skills:
      "نموذج تجريبي توضيحي للمهارات والخبرات المتاحة للتقديم والتواصل عبر الدليل.",
    phone: "01062049652",
    whatsApp: "201062049652",
    location: "مغاغة",
  },
  {
    id: "seeker_2",
    name: "باحث عن عمل (نموذج توضيحي 2)",
    jobDesired: "سائق دليفري / مشاوير",
    age: "25 سنة",
    education: "مؤهل متوسط",
    skills: "نموذج تجريبي يوضح إمكانية إضافة بيانات الباحثين عن عمل والخدمات.",
    phone: "01062049652",
    whatsApp: "201062049652",
    location: "مغاغة",
  },
];

export const INITIAL_JOB_VACANCIES = [
  {
    id: "vacancy_1",
    title: "طلب موظف كاشير (فرصة عمل تجريبية)",
    businessName: "نشاط تجاري (نموذج رقم 1)",
    requirements: "شروط تجريبية للتوضيح - حسن الأسلوب والالتزام بالعمل.",
    workType: "صباحي - 8 ساعات",
    salary: "مرتب مجزي + عمولة",
    location: "مغاغة",
    phone: "01062049652",
    whatsApp: "201062049652",
  },
  {
    id: "vacancy_2",
    title: "طلب مساعد مبيعات (فرصة عمل تجريبية)",
    businessName: "نشاط تجاري (نموذج رقم 2)",
    requirements: "متطلبات تجريبية - النظافة والسرعة في العمل.",
    workType: "مسائي - 8 ساعات",
    salary: "يحدد في المقابلة",
    location: "مغاغة",
    phone: "01062049652",
    whatsApp: "201062049652",
  },
];

export const DOCTOR_CATEGORIES = [
  { id: "surgery_urology", name: "الجراحة والمسالك", icon: "fa-user-nurse" },
  { id: "physical_therapy", name: "العلاج الطبيعي", icon: "fa-child-reaching" },
  { id: "pediatrics", name: "الأطفال", icon: "fa-baby" },
  { id: "gynecology", name: "النساء والتوليد", icon: "fa-venus" },
  {
    id: "female_gynecology",
    name: "طبيبات النساء والتوليد",
    icon: "fa-user-doctor",
  },
  { id: "ent", name: "الأنف والأذن والحنجرة", icon: "fa-head-side-cough" },
  { id: "ophthalmology", name: "العيون", icon: "fa-eye" },
  { id: "dental", name: "الأسنان", icon: "fa-tooth" },
  {
    id: "internal_chest",
    name: "الباطنة والصدر والحميات",
    icon: "fa-stethoscope",
  },
  { id: "neurology", name: "المخ والأعصاب", icon: "fa-brain" },
  { id: "orthopedics", name: "العظام", icon: "fa-bone" },
  { id: "dermatology", name: "الجلدية", icon: "fa-hand-dots" },
  { id: "labs", name: "معامل التحاليل", icon: "fa-vial-virus" },
];

export const INITIAL_DOCTORS = [
  {
    id: "doc_surg_1",
    name: "د. أحمد بدر الدين",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "ش المحطة",
    phone: "01013550123",
  },
  {
    id: "doc_surg_2",
    name: "د. ثروت جرجس",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "ش الدسوقي",
    phone: "01223582918",
  },
  {
    id: "doc_surg_3",
    name: "د. جابر يوسف",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "ش عبد العظيم",
    phone: "01006566223",
  },
  {
    id: "doc_surg_4",
    name: "د. جمال أبو هشيمة",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "ش طه حسين",
    phone: "01001289625",
  },
  {
    id: "doc_surg_5",
    name: "د. حسين عبد الرازق",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "ش طه حسين",
    phone: "01005763957",
  },
  {
    id: "doc_surg_6",
    name: "د. خالد نجيب",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "ش المحطة",
    phone: "3553664",
  },
  {
    id: "doc_surg_7",
    name: "د. خلف ياسين",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "ش المركز الطبي",
    phone: "01003092109",
  },
  {
    id: "doc_surg_8",
    name: "د. رجب مهني",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "ش طه حسين",
    phone: "01010267847",
  },
  {
    id: "doc_surg_9",
    name: "د. ريمون ميلاد عطية",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "ش ناعوم – أمام جامع قاسم المصري",
    phone: "01228983829",
  },
  {
    id: "doc_surg_10",
    name: "د. صموائيل جرجس",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "ش الكوبري القديم",
    phone: "01203749812",
  },
  {
    id: "doc_surg_11",
    name: "د. صموائيل مريد",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "ش الجمهورية",
    phone: "01005632530",
  },
  {
    id: "doc_surg_12",
    name: "د. عاطف جرجس بقطر",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "ش السلام",
    phone: "01224538712",
  },
  {
    id: "doc_surg_13",
    name: "د. عاطف نصر الله",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "ش الجمهورية",
    phone: "—",
  },
  {
    id: "doc_surg_14",
    name: "د. عمرو حمدي",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "ش المركز الطبي",
    phone: "01113183042",
  },
  {
    id: "doc_surg_15",
    name: "د. عصام رشدي",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "ش أسواق حبيبة",
    phone: "01224538712",
  },
  {
    id: "doc_surg_16",
    name: "د. فايز أبو زيد",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "ش طه حسين",
    phone: "01113183042",
  },
  {
    id: "doc_surg_17",
    name: "د. كميل كرومو",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "ش السلام",
    phone: "01002344295",
  },
  {
    id: "doc_surg_18",
    name: "د. محمد أحمد مهدي",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "ش طه حسين",
    phone: "01025143132",
  },
  {
    id: "doc_surg_19",
    name: "د. محمد العربي",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "ش طه حسين",
    phone: "01001156139",
  },
  {
    id: "doc_surg_20",
    name: "د. محمد رجب",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "ش طه حسين",
    phone: "—",
  },
  {
    id: "doc_surg_21",
    name: "د. محمد نجاتي",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "ش المركز الطبي",
    phone: "01003092109",
  },
  {
    id: "doc_surg_22",
    name: "د. محمود عرفة",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "بجوار التأمينات",
    phone: "01068457390 / 01118873298",
  },
  {
    id: "doc_surg_23",
    name: "د. مصطفى السيد",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "قليني",
    phone: "01067593630",
  },
  {
    id: "doc_surg_24",
    name: "د. مصطفى خيري",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "ش السلام",
    phone: "01094545908",
  },
  {
    id: "doc_surg_25",
    name: "د. ناصر زغلول",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "ش عبد العظيم",
    phone: "01113148658",
  },
  {
    id: "doc_surg_26",
    name: "د. هشام حسن",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "قليني",
    phone: "01098237830",
  },
  {
    id: "doc_surg_27",
    name: "د. وليد عبد الرحمن",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "ش الكوبري الجديد",
    phone: "01094559065",
  },
  {
    id: "doc_surg_28",
    name: "د. محمد رجب – جراحة عامة",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "شارع السلام – ميدان الحمامة",
    phone: "01012039123",
  },
  {
    id: "doc_surg_29",
    name: "د. أيمن معتوق – استشاري جراحة تجميل",
    specialty: "الجراحة والمسالك",
    specialtyId: "surgery_urology",
    address: "العبور، شارع المستشارين، أمام مسجد عباد الرحمن",
    phone: "01125076265",
  },

  // أطباء العلاج الطبيعي
  {
    id: "doc_phys_1",
    name: "د. أحمد حامد غرياني",
    specialty: "العلاج الطبيعي",
    specialtyId: "physical_therapy",
    address: "ش أدهم البحري",
    phone: "01148632551",
  },
  {
    id: "doc_phys_2",
    name: "د. أمير حنا جندي",
    specialty: "العلاج الطبيعي",
    specialtyId: "physical_therapy",
    address: "ش السنترال",
    phone: "01010810934",
  },
  {
    id: "doc_phys_3",
    name: "د. بيتر ناجي توفيق",
    specialty: "العلاج الطبيعي",
    specialtyId: "physical_therapy",
    address: "ش السنترال",
    phone: "0863564595",
  },
  {
    id: "doc_phys_4",
    name: "د. سوزان زكريا",
    specialty: "العلاج الطبيعي",
    specialtyId: "physical_therapy",
    address: "ش الجمهورية",
    phone: "01224280788",
  },
  {
    id: "doc_phys_5",
    name: "د. صفاء حجاج رمضان",
    specialty: "العلاج الطبيعي",
    specialtyId: "physical_therapy",
    address: "ش السلام",
    phone: "01156846364",
  },
  {
    id: "doc_phys_6",
    name: "د. فؤاد هريدي",
    specialty: "العلاج الطبيعي",
    specialtyId: "physical_therapy",
    address: "ش الكنيسة",
    phone: "01112582585",
  },
  {
    id: "doc_phys_7",
    name: "د. محمد أبو الوفا",
    specialty: "العلاج الطبيعي",
    specialtyId: "physical_therapy",
    address: "ش الجمهورية",
    phone: "01008684436",
  },
  {
    id: "doc_phys_8",
    name: "د. محمد عبد الحليم",
    specialty: "العلاج الطبيعي",
    specialtyId: "physical_therapy",
    address: "ش الثورة",
    phone: "01097006052",
  },
  {
    id: "doc_phys_9",
    name: "د. مصطفي خضر",
    specialty: "العلاج الطبيعي",
    specialtyId: "physical_therapy",
    address: "ش السلام",
    phone: "01284393909",
  },
  {
    id: "doc_phys_10",
    name: "د. نهي نجاتي علي",
    specialty: "العلاج الطبيعي",
    specialtyId: "physical_therapy",
    address: "ش الجمهورية",
    phone: "01012726975",
  },
  {
    id: "doc_phys_11",
    name: "د. ياسمين حمدي الشيمي",
    specialty: "العلاج الطبيعي",
    specialtyId: "physical_therapy",
    address: "ش الثورة",
    phone: "01125800480",
  },

  // أطباء الأطفال
  {
    id: "doc_ped_1",
    name: "د. أحمد المنياوي",
    specialty: "الأطفال",
    specialtyId: "pediatrics",
    address: "ش طه حسين",
    phone: "010066776516",
  },
  {
    id: "doc_ped_2",
    name: "د. أحمد حجاج",
    specialty: "الأطفال",
    specialtyId: "pediatrics",
    address: "ش السلام",
    phone: "01101347380",
  },
  {
    id: "doc_ped_3",
    name: "د. الحسيني مجاور",
    specialty: "الأطفال",
    specialtyId: "pediatrics",
    address: "ش الجمهورية",
    phone: "01112401226",
  },
  {
    id: "doc_ped_4",
    name: "د. السيد جمال",
    specialty: "الأطفال",
    specialtyId: "pediatrics",
    address: "أعلى المصرية للصرافة",
    phone: "01119703825",
  },
  {
    id: "doc_ped_5",
    name: "د. أيمن لويز",
    specialty: "الأطفال",
    specialtyId: "pediatrics",
    address: "ش السلام",
    phone: "01226751189",
  },
  {
    id: "doc_ped_6",
    name: "د. بهاء أبو العلا",
    specialty: "الأطفال",
    specialtyId: "pediatrics",
    address: "ش طه حسين",
    phone: "01024916491",
  },
  {
    id: "doc_ped_7",
    name: "د. جمال بهيج",
    specialty: "الأطفال",
    specialtyId: "pediatrics",
    address: "ش طه حسين",
    phone: "3558771",
  },
  {
    id: "doc_ped_8",
    name: "د. رضا فاروق البنا",
    specialty: "الأطفال",
    specialtyId: "pediatrics",
    address: "ش المحطة",
    phone: "01003780316",
  },
  {
    id: "doc_ped_9",
    name: "د. سليمان عبد الغفار",
    specialty: "الأطفال",
    specialtyId: "pediatrics",
    address: "ش طه حسين",
    phone: "01228054346",
  },
  {
    id: "doc_ped_10",
    name: "د. عزت سعد",
    specialty: "الأطفال",
    specialtyId: "pediatrics",
    address: "ش المحطة",
    phone: "01146543797",
  },
  {
    id: "doc_ped_11",
    name: "د. عزة عمر طرة",
    specialty: "الأطفال",
    specialtyId: "pediatrics",
    address: "ش الجمهورية",
    phone: "01007216725",
  },
  {
    id: "doc_ped_12",
    name: "د. عصام شكري نصر الله",
    specialty: "الأطفال",
    specialtyId: "pediatrics",
    address: "ش السلام",
    phone: "35500830",
  },
  {
    id: "doc_ped_13",
    name: "د. على شعبان",
    specialty: "الأطفال",
    specialtyId: "pediatrics",
    address: "ش طه حسين",
    phone: "01159167511",
  },
  {
    id: "doc_ped_14",
    name: "د. على حسن أبو شوق",
    specialty: "الأطفال",
    specialtyId: "pediatrics",
    address: "آخر ش الجمهورية",
    phone: "01280010439",
  },
  {
    id: "doc_ped_15",
    name: "د. عمرو مجدي كريم",
    specialty: "الأطفال",
    specialtyId: "pediatrics",
    address: "ش الجمهورية",
    phone: "—",
  },
  {
    id: "doc_ped_16",
    name: "د. غالي حنا",
    specialty: "الأطفال",
    specialtyId: "pediatrics",
    address: "ش الجمهورية",
    phone: "01003570744",
  },
  {
    id: "doc_ped_17",
    name: "د. محمود محمد عيد",
    specialty: "الأطفال",
    specialtyId: "pediatrics",
    address: "ميدان الحمامة",
    phone: "0114678851",
  },
  {
    id: "doc_ped_18",
    name: "د. مدحت عدلي",
    specialty: "الأطفال",
    specialtyId: "pediatrics",
    address: "ش أسواق حبيبة",
    phone: "01228054346",
  },
  {
    id: "doc_ped_19",
    name: "د. هاني حسين",
    specialty: "الأطفال",
    specialtyId: "pediatrics",
    address: "ش طه حسين",
    phone: "01093642304",
  },
  {
    id: "doc_ped_20",
    name: "د. نشوى الطحاوي",
    specialty: "الأطفال",
    specialtyId: "pediatrics",
    address: "ش طه حسين",
    phone: "3558771",
  },
  {
    id: "doc_ped_21",
    name: "د. يوسف شحاتة",
    specialty: "الأطفال",
    specialtyId: "pediatrics",
    address: "ش عبد العظيم",
    phone: "01274376960",
  },

  // أطباء النساء والتوليد
  {
    id: "doc_gyn_1",
    name: "مركز د. محمود البطل",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش الجمهورية",
    phone: "01062124250",
  },
  {
    id: "doc_gyn_2",
    name: "د. احمد حسن عبد الصمد",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش السلام",
    phone: "01204884931",
  },
  {
    id: "doc_gyn_3",
    name: "د. أحمد فوزي",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "بجوار بنك مصر",
    phone: "01204171944",
  },
  {
    id: "doc_gyn_4",
    name: "د. أحمد مرزوق",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش الجمهورية",
    phone: "01110993693",
  },
  {
    id: "doc_gyn_5",
    name: "د. احمد هاشم",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش طه حسين",
    phone: "01100055220",
  },
  {
    id: "doc_gyn_6",
    name: "د. أسامة إبراهيم",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "مغاغة",
    phone: "01011221723",
  },
  {
    id: "doc_gyn_7",
    name: "د. ارميا سمسوم",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "صيدلية الملطاوي",
    phone: "01006520807",
  },
  {
    id: "doc_gyn_8",
    name: "د. امير حبيب",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش عبد العظيم",
    phone: "—",
  },
  {
    id: "doc_gyn_9",
    name: "د. حسن العلوي",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش طه حسين",
    phone: "01117507960",
  },
  {
    id: "doc_gyn_10",
    name: "د. حسين الليثي",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش طه حسين",
    phone: "01005826837",
  },
  {
    id: "doc_gyn_11",
    name: "د. ريمون ميلاد عطية",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش ناعوم أمام جامع قاسم المصري",
    phone: "01228983829",
  },
  {
    id: "doc_gyn_12",
    name: "د. سعد الجيلاتي",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش الدسوقي",
    phone: "01068700595",
  },
  {
    id: "doc_gyn_13",
    name: "د. صبحي حبيب",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش الجمهورية",
    phone: "01227007050",
  },
  {
    id: "doc_gyn_14",
    name: "د. طاهر عبد القادر",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش الجمهورية",
    phone: "01002211382",
  },
  {
    id: "doc_gyn_15",
    name: "د. طه عبد المعبود",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش طه حسين",
    phone: "01122702344",
  },
  {
    id: "doc_gyn_16",
    name: "د. علواني السنوسي",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش المحطة",
    phone: "3553718",
  },
  {
    id: "doc_gyn_17",
    name: "د. كريم المحمدي",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش طه حسين",
    phone: "01112428446",
  },
  {
    id: "doc_gyn_18",
    name: "د. لطفي ساويرس",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش الجمهورية",
    phone: "01222895725",
  },
  {
    id: "doc_gyn_19",
    name: "د. ماركو نشأت",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش الانجيلية",
    phone: "01284014077",
  },
  {
    id: "doc_gyn_20",
    name: "د. محمد أحمد زين",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش الشبان المسلمين",
    phone: "01229367096",
  },
  {
    id: "doc_gyn_21",
    name: "د. محمد توفيق جاد الرب",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش طه حسين",
    phone: "3555220",
  },
  {
    id: "doc_gyn_22",
    name: "د. محمد حكيم",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش السلام",
    phone: "01111994686",
  },
  {
    id: "doc_gyn_23",
    name: "د. محمد سعيد زيدان",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش الجمهورية",
    phone: "01222902276",
  },
  {
    id: "doc_gyn_24",
    name: "د. محمد رمضان",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش السلام",
    phone: "01006592458",
  },
  {
    id: "doc_gyn_25",
    name: "د. محمد سيد دياب",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش طه حسين",
    phone: "01006216293",
  },
  {
    id: "doc_gyn_26",
    name: "د. محمد على توفيق",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "آبا البلد",
    phone: "01148721708",
  },
  {
    id: "doc_gyn_27",
    name: "د. محمد نور الدين",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش طه حسين",
    phone: "01013571350",
  },
  {
    id: "doc_gyn_28",
    name: "د. محمود زغلول ابو الحسن",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش السلام",
    phone: "01204404422",
  },
  {
    id: "doc_gyn_29",
    name: "د. مراد عدلي",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش الجمهورية",
    phone: "01222442460",
  },
  {
    id: "doc_gyn_30",
    name: "د. مينا عبيد",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش الكنيسة",
    phone: "01226272819",
  },
  {
    id: "doc_gyn_31",
    name: "د. مينا ناجي ناروز",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش طه حسين",
    phone: "01220136189",
  },
  {
    id: "doc_gyn_32",
    name: "د. ناصف عدلي",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش الجمهورية",
    phone: "01001544932",
  },
  {
    id: "doc_gyn_33",
    name: "د. نجيب ياسر نجيب",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش الجمهورية",
    phone: "—",
  },
  {
    id: "doc_gyn_34",
    name: "د. نزيه الجنايني",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ميدان الحمامة",
    phone: "01112375390",
  },
  {
    id: "doc_gyn_35",
    name: "د. هاني ظريف",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش السلام",
    phone: "01203943454",
  },
  {
    id: "doc_gyn_36",
    name: "د. ياسر نجيب",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "ش الجمهورية",
    phone: "01062336666",
  },
  {
    id: "doc_gyn_37",
    name: "د. شيرين رشدي",
    specialty: "النساء والتوليد",
    specialtyId: "gynecology",
    address: "مغاغة",
    phone: "01271997278",
  },

  // أطباء الأنف والأذن والحنجرة
  {
    id: "doc_ent_1",
    name: "د. أحمد عادل صادق",
    specialty: "الأنف والأذن والحنجرة",
    specialtyId: "ent",
    address: "ش المحطة",
    phone: "01003518769",
  },
  {
    id: "doc_ent_2",
    name: "د. جورج نصر الله",
    specialty: "الأنف والأذن والحنجرة",
    specialtyId: "ent",
    address: "ش الجمهورية",
    phone: "—",
  },
  {
    id: "doc_ent_3",
    name: "د. حسام فهمي",
    specialty: "الأنف والأذن والحنجرة",
    specialtyId: "ent",
    address: "ش الجمهورية",
    phone: "01145201781",
  },
  {
    id: "doc_ent_4",
    name: "د. صموئيل سعيد",
    specialty: "الأنف والأذن والحنجرة",
    specialtyId: "ent",
    address: "ش عبد العظيم",
    phone: "01270634739",
  },
  {
    id: "doc_ent_5",
    name: "د. طارق منصور",
    specialty: "الأنف والأذن والحنجرة",
    specialtyId: "ent",
    address: "ش الجمهورية",
    phone: "01112528839",
  },
  {
    id: "doc_ent_6",
    name: "د. مايكل جبران",
    specialty: "الأنف والأذن والحنجرة",
    specialtyId: "ent",
    address: "ش السلام",
    phone: "01221149846",
  },
  {
    id: "doc_ent_7",
    name: "د. محمد فايز",
    specialty: "الأنف والأذن والحنجرة",
    specialtyId: "ent",
    address: "ش السلام",
    phone: "—",
  },
  {
    id: "doc_ent_8",
    name: "د. محمد يحيى الشمي",
    specialty: "الأنف والأذن والحنجرة",
    specialtyId: "ent",
    address: "ش طه حسين",
    phone: "01140822383",
  },
  {
    id: "doc_ent_9",
    name: "د. ممدوح أبو الروس",
    specialty: "الأنف والأذن والحنجرة",
    specialtyId: "ent",
    address: "ش الجمهورية",
    phone: "01002047572",
  },
  {
    id: "doc_ent_10",
    name: "د. مينا سمير نجيب",
    specialty: "الأنف والأذن والحنجرة",
    specialtyId: "ent",
    address: "ش الجمهورية",
    phone: "01014310433",
  },

  // أطباء العيون
  {
    id: "doc_oph_1",
    name: "د. أحمد البحار",
    specialty: "العيون",
    specialtyId: "ophthalmology",
    address: "ش التأمينات",
    phone: "01289829783",
  },
  {
    id: "doc_oph_2",
    name: "د. خالد عبد العظيم",
    specialty: "العيون",
    specialtyId: "ophthalmology",
    address: "ش السلام",
    phone: "01156569577",
  },
  {
    id: "doc_oph_3",
    name: "د. شريف صابر",
    specialty: "العيون",
    specialtyId: "ophthalmology",
    address: "ش المحطة",
    phone: "3551247",
  },
  {
    id: "doc_oph_4",
    name: "د. عبد اللطيف خميس",
    specialty: "العيون",
    specialtyId: "ophthalmology",
    address: "ش الجمهورية",
    phone: "01154964621",
  },
  {
    id: "doc_oph_5",
    name: "د. عمرو الجارحي",
    specialty: "العيون",
    specialtyId: "ophthalmology",
    address: "ش طه حسين",
    phone: "0111977764",
  },
  {
    id: "doc_oph_6",
    name: "د. عمرو عبد الرحمن",
    specialty: "العيون",
    specialtyId: "ophthalmology",
    address: "ش السلام",
    phone: "01015914471",
  },
  {
    id: "doc_oph_7",
    name: "د. محمد حسن عبد العال",
    specialty: "العيون",
    specialtyId: "ophthalmology",
    address: "ش المحطة",
    phone: "01006644650",
  },
  {
    id: "doc_oph_8",
    name: "د. محمود المغربي",
    specialty: "العيون",
    specialtyId: "ophthalmology",
    address: "ش السلام",
    phone: "01208564488",
  },
  {
    id: "doc_oph_9",
    name: "د. محمود عبد المجيد",
    specialty: "العيون",
    specialtyId: "ophthalmology",
    address: "ش طه حسين",
    phone: "01281141841",
  },
  {
    id: "doc_oph_10",
    name: "د. محمود فوزي",
    specialty: "العيون",
    specialtyId: "ophthalmology",
    address: "ش السلام",
    phone: "01123542695",
  },

  // أطباء الأسنان
  {
    id: "doc_den_1",
    name: "د. أبانوب جمال",
    specialty: "الأسنان",
    specialtyId: "dental",
    address: "ش الجمهورية",
    phone: "—",
  },
  {
    id: "doc_den_2",
    name: "د. أبو بكر حجاج",
    specialty: "الأسنان",
    specialtyId: "dental",
    address: "ش الجمهورية",
    phone: "—",
  },
  {
    id: "doc_den_3",
    name: "د. إبراهيم أحمد حماد",
    specialty: "الأسنان",
    specialtyId: "dental",
    address: "ش السلام",
    phone: "—",
  },
  {
    id: "doc_den_4",
    name: "د. أحمد الخياط",
    specialty: "الأسنان",
    specialtyId: "dental",
    address: "ش الدسوقي",
    phone: "3553417",
  },
  {
    id: "doc_den_5",
    name: "د. أحمد جمال حمزاوي",
    specialty: "الأسنان",
    specialtyId: "dental",
    address: "ش الجمهورية",
    phone: "3556655",
  },
  {
    id: "doc_den_6",
    name: "د. أحمد جمال مكاوي",
    specialty: "الأسنان",
    specialtyId: "dental",
    address: "ش السلام",
    phone: "01154702313",
  },
  {
    id: "doc_den_7",
    name: "د. أحمد محمد على",
    specialty: "الأسنان",
    specialtyId: "dental",
    address: "ش التأمينات",
    phone: "—",
  },
  {
    id: "doc_den_8",
    name: "دكتورة/ إسراء محمد عبد الحفيظ",
    specialty: "الأسنان",
    specialtyId: "dental",
    address: "ش السلام",
    phone: "01002977699",
  },
  {
    id: "doc_den_9",
    name: "د. إاسلام العمدة",
    specialty: "الأسنان",
    specialtyId: "dental",
    address: "ش الجمهورية",
    phone: "—",
  },
  {
    id: "doc_den_10",
    name: "د. أشرف عفيفي",
    specialty: "الأسنان",
    specialtyId: "dental",
    address: "ش السنترال",
    phone: "—",
  },
  {
    id: "doc_den_11",
    name: "د. انطوني محروس",
    specialty: "الأسنان",
    specialtyId: "dental",
    address: "ش الجمهورية",
    phone: "01282648484",
  },
  {
    id: "doc_den_12",
    name: "دكتورة/ إيمان سيد مختار",
    specialty: "الأسنان",
    specialtyId: "dental",
    address: "ش الجمهورية",
    phone: "3567750",
  },
  {
    id: "doc_den_13",
    name: "د. بهاء بحيري",
    specialty: "الأسنان",
    specialtyId: "dental",
    address: "ش الجمهورية",
    phone: "01017151312",
  },
  {
    id: "doc_den_14",
    name: "د. شريف شهدي",
    specialty: "الأسنان",
    specialtyId: "dental",
    address: "ش السلام",
    phone: "3555100",
  },
  {
    id: "doc_den_15",
    name: "د. طاهر عبد الله",
    specialty: "الأسنان",
    specialtyId: "dental",
    address: "ش الجمهورية",
    phone: "01158986997",
  },
  {
    id: "doc_den_16",
    name: "د. عادل عبد العظيم",
    specialty: "الأسنان",
    specialtyId: "dental",
    address: "ش عبد العظيم",
    phone: "—",
  },
  {
    id: "doc_den_17",
    name: "د. عصام مطيع صبره",
    specialty: "الأسنان",
    specialtyId: "dental",
    address: "ش السلام",
    phone: "01020539334",
  },

  // أطباء الباطنة والصدر والحميات
  {
    id: "doc_int_1",
    name: "د. أحمد ربيع",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش نوح",
    phone: "01009545086",
  },
  {
    id: "doc_int_2",
    name: "د. أحمد ماهر",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش طه حسين",
    phone: "01200814720",
  },
  {
    id: "doc_int_3",
    name: "د. أحمد محمد كامل مرسي",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش السلام",
    phone: "01033081515",
  },
  {
    id: "doc_int_4",
    name: "د. إسحق عبد الله",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش الجمهورية",
    phone: "01005886162",
  },
  {
    id: "doc_int_5",
    name: "د. أشرف أنيس",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش قاسم المصري",
    phone: "01144637789",
  },
  {
    id: "doc_int_6",
    name: "د. أيمن محمد عبد الحافظ",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش السلام",
    phone: "01024737575",
  },
  {
    id: "doc_int_7",
    name: "د. حمدى مقرب",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش الجمهورية",
    phone: "3563090",
  },
  {
    id: "doc_int_8",
    name: "د. خالد المغربي",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش السلام",
    phone: "3555203",
  },
  {
    id: "doc_int_9",
    name: "د. رضا حسن",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش السلام",
    phone: "—",
  },
  {
    id: "doc_int_10",
    name: "د. رضا مفتاح",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش السلام",
    phone: "01111493056",
  },
  {
    id: "doc_int_11",
    name: "د. روماني ثابت",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش عبد العظيم",
    phone: "3556437",
  },
  {
    id: "doc_int_12",
    name: "دكتورة/ زينب حسن كامل",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش الدسوقي",
    phone: "01140018099",
  },
  {
    id: "doc_int_13",
    name: "د. صفوت سنبل",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش التأمينات",
    phone: "6551019",
  },
  {
    id: "doc_int_14",
    name: "د. صلاح دسوقي",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش السلام",
    phone: "01143090167",
  },
  {
    id: "doc_int_15",
    name: "د. عاطف عبد السيد",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش عبد العظيم",
    phone: "01218606217",
  },
  {
    id: "doc_int_16",
    name: "د. عبد العزيز فهمي",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش طه حسين",
    phone: "01069354349",
  },
  {
    id: "doc_int_17",
    name: "دكتورة/ عزة عويس",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش الإعدادية بنات",
    phone: "01226625241",
  },
  {
    id: "doc_int_18",
    name: "د. علاء أبو غنيمة",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش الشواني",
    phone: "01222750301",
  },
  {
    id: "doc_int_19",
    name: "د. علاء راضي",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش طه حسين",
    phone: "01281431331",
  },
  {
    id: "doc_int_20",
    name: "د. على عبد العظيم",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش طه حسين",
    phone: "01003564805",
  },
  {
    id: "doc_int_21",
    name: "د. على نجيب",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش السلام",
    phone: "01201911567",
  },
  {
    id: "doc_int_22",
    name: "د. محمد مفرح",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش السلام",
    phone: "01110797001",
  },
  {
    id: "doc_int_23",
    name: "د. محمود رجب",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش الكوبري الجديد",
    phone: "01227018183",
  },
  {
    id: "doc_int_24",
    name: "د. محمود محمد حسين",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش السلام",
    phone: "01121621894",
  },
  {
    id: "doc_int_25",
    name: "د. محمود معتوق",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "العبور",
    phone: "01009121289",
  },
  {
    id: "doc_int_26",
    name: "د. مجدي فؤاد شلبي",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش التأمينات",
    phone: "01282615399",
  },
  {
    id: "doc_int_27",
    name: "د. مصطفى جمال",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش الدسوقي",
    phone: "01202430951",
  },
  {
    id: "doc_int_28",
    name: "د. مصطفى كمال الصغير",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش المحطة",
    phone: "—",
  },
  {
    id: "doc_int_29",
    name: "د. ممدوح الشوربجي",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش المحطة",
    phone: "3553606",
  },
  {
    id: "doc_int_30",
    name: "د. ناصر على عبد اللطيف",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش طه حسين",
    phone: "01061325630",
  },
  {
    id: "doc_int_31",
    name: "د. ياسر عبد الغني",
    specialty: "الباطنة والصدر والحميات",
    specialtyId: "internal_chest",
    address: "ش المحطة",
    phone: "01149021078",
  },

  // أطباء المخ والأعصاب
  {
    id: "doc_neuro_1",
    name: "د. حسين سعيد",
    specialty: "المخ والأعصاب",
    specialtyId: "neurology",
    address: "ميدان الحمامة",
    phone: "01156704586",
  },
  {
    id: "doc_neuro_2",
    name: "د. زين الدين سعيد",
    specialty: "المخ والأعصاب",
    specialtyId: "neurology",
    address: "ش الدسوقي",
    phone: "01008265998",
  },
  {
    id: "doc_neuro_3",
    name: "د. سامح عياد",
    specialty: "المخ والأعصاب",
    specialtyId: "neurology",
    address: "ش الجمهورية",
    phone: "01221008776",
  },
  {
    id: "doc_neuro_4",
    name: "د. صموئيل سامح عياد",
    specialty: "المخ والأعصاب",
    specialtyId: "neurology",
    address: "ش الجمهورية",
    phone: "01220935867",
  },
  {
    id: "doc_neuro_5",
    name: "د. ماهر شكري",
    specialty: "المخ والأعصاب",
    specialtyId: "neurology",
    address: "ش المحطة",
    phone: "01061840722",
  },
  {
    id: "doc_neuro_6",
    name: "د. محمد عبد الحميد",
    specialty: "المخ والأعصاب",
    specialtyId: "neurology",
    address: "ش طه حسين",
    phone: "01151148725",
  },
  {
    id: "doc_neuro_7",
    name: "د. هاني الأشعل",
    specialty: "المخ والأعصاب",
    specialtyId: "neurology",
    address: "أمام قليني",
    phone: "01147334974",
  },
  {
    id: "doc_neuro_8",
    name: "د. جوزيف ممدوح إلياس",
    specialty: "المخ والأعصاب",
    specialtyId: "neurology",
    address: "مغاغة",
    phone: "01020118604",
  },

  // أطباء العظام
  {
    id: "doc_ortho_1",
    name: "د. أحمد أبو العلا",
    specialty: "العظام",
    specialtyId: "orthopedics",
    address: "ش السلام",
    phone: "3553417",
  },
  {
    id: "doc_ortho_2",
    name: "د. أحمد أمين",
    specialty: "العظام",
    specialtyId: "orthopedics",
    address: "ش الصنايع",
    phone: "3556655",
  },
  {
    id: "doc_ortho_3",
    name: "د. أحمد جمال",
    specialty: "العظام",
    specialtyId: "orthopedics",
    address: "أمام مستشفى قليني",
    phone: "01018589511",
  },
  {
    id: "doc_ortho_4",
    name: "د. أحمد محمد حسنين",
    specialty: "العظام",
    specialtyId: "orthopedics",
    address: "ش السلام",
    phone: "01154702313",
  },
  {
    id: "doc_ortho_5",
    name: "د. أحمد عبد العظيم",
    specialty: "العظام",
    specialtyId: "orthopedics",
    address: "ش السلام",
    phone: "—",
  },
  {
    id: "doc_ortho_6",
    name: "د. أحمد عويس",
    specialty: "العظام",
    specialtyId: "orthopedics",
    address: "ش طه حسين",
    phone: "01116741414",
  },
  {
    id: "doc_ortho_7",
    name: "د. أحمد عيد",
    specialty: "العظام",
    specialtyId: "orthopedics",
    address: "ش الجمهورية",
    phone: "01091974044",
  },
  {
    id: "doc_ortho_8",
    name: "د. أحمد نادي الشويخ",
    specialty: "العظام",
    specialtyId: "orthopedics",
    address: "ش السلام",
    phone: "01017151312",
  },
  {
    id: "doc_ortho_9",
    name: "د. أشرف سعيد",
    specialty: "العظام",
    specialtyId: "orthopedics",
    address: "ش أسواق حبيبة",
    phone: "—",
  },
  {
    id: "doc_ortho_10",
    name: "د. إمام درويش",
    specialty: "العظام",
    specialtyId: "orthopedics",
    address: "ش السلام",
    phone: "3555100",
  },
  {
    id: "doc_ortho_11",
    name: "د. إيهاب الشال",
    specialty: "العظام",
    specialtyId: "orthopedics",
    address: "ش عبد العظيم",
    phone: "—",
  },
  {
    id: "doc_ortho_12",
    name: "د. رأفت عبد اللطيف",
    specialty: "العظام",
    specialtyId: "orthopedics",
    address: "ش التأمينات",
    phone: "01020539334",
  },
  {
    id: "doc_ortho_13",
    name: "د. شريف عاشور",
    specialty: "العظام",
    specialtyId: "orthopedics",
    address: "ش التأمينات",
    phone: "01019395977",
  },
  {
    id: "doc_ortho_14",
    name: "د. عبد الله جلال",
    specialty: "العظام",
    specialtyId: "orthopedics",
    address: "ش الجمهورية",
    phone: "01287942060",
  },
  {
    id: "doc_ortho_15",
    name: "د. عبد الوهاب عبد العال",
    specialty: "العظام",
    specialtyId: "orthopedics",
    address: "ش الجمهورية",
    phone: "01110381581",
  },
  {
    id: "doc_ortho_16",
    name: "د. عمر جيرة",
    specialty: "العظام",
    specialtyId: "orthopedics",
    address: "ش الجمهورية",
    phone: "0863552966",
  },
  {
    id: "doc_ortho_17",
    name: "د. محمد أحمد عيد",
    specialty: "العظام",
    specialtyId: "orthopedics",
    address: "ش آدهم",
    phone: "01091974044",
  },
  {
    id: "doc_ortho_18",
    name: "د. محمد سيد خميس",
    specialty: "العظام",
    specialtyId: "orthopedics",
    address: "ش الزهور",
    phone: "01289086172",
  },
  {
    id: "doc_ortho_19",
    name: "د. محمد كمال نظير",
    specialty: "العظام",
    specialtyId: "orthopedics",
    address: "ش الجمهورية",
    phone: "01118116559",
  },
  {
    id: "doc_ortho_20",
    name: "د. محمد لكلوك",
    specialty: "العظام",
    specialtyId: "orthopedics",
    address: "ش المركز الطبي",
    phone: "01002679146",
  },
  {
    id: "doc_ortho_21",
    name: "د. محمد معوض",
    specialty: "العظام",
    specialtyId: "orthopedics",
    address: "ش طه حسين",
    phone: "01020622562",
  },
  {
    id: "doc_ortho_22",
    name: "د. نادي الشويخ",
    specialty: "العظام",
    specialtyId: "orthopedics",
    address: "ش السلام",
    phone: "01017151312",
  },

  // أطباء الجلدية
  {
    id: "doc_derm_1",
    name: "د. خالد محمد توفيق",
    specialty: "الجلدية",
    specialtyId: "dermatology",
    address: "ش الجمهورية",
    phone: "3567750",
  },
  {
    id: "doc_derm_2",
    name: "د. صموائيل لوزة",
    specialty: "الجلدية",
    specialtyId: "dermatology",
    address: "ش الجمهورية",
    phone: "01286708590",
  },
  {
    id: "doc_derm_3",
    name: "د. طارق العماوي",
    specialty: "الجلدية",
    specialtyId: "dermatology",
    address: "ش المحطة",
    phone: "—",
  },
  {
    id: "doc_derm_4",
    name: "د. عبد الرازق كامل",
    specialty: "الجلدية",
    specialtyId: "dermatology",
    address: "ش المحطة",
    phone: "3556881",
  },
  {
    id: "doc_derm_5",
    name: "د. محمود حمدي منتصر",
    specialty: "الجلدية",
    specialtyId: "dermatology",
    address: "ش طه حسين",
    phone: "01009463000",
  },
  {
    id: "doc_derm_6",
    name: "د. ناجح مكرم محمد",
    specialty: "الجلدية",
    specialtyId: "dermatology",
    address: "ش السلام",
    phone: "01153507650",
  },
  {
    id: "doc_derm_7",
    name: "دكتورة/ نجوي عبد الفتاح",
    specialty: "الجلدية",
    specialtyId: "dermatology",
    address: "ش طه حسين",
    phone: "01288528821",
  },
  {
    id: "doc_derm_8",
    name: "دكتورة/ هناء كرم الدين",
    specialty: "الجلدية",
    specialtyId: "dermatology",
    address: "ش طه حسين",
    phone: "—",
  },
  {
    id: "doc_derm_9",
    name: "د. كرستينا كرومر",
    specialty: "الجلدية",
    specialtyId: "dermatology",
    address: "ش عبد العظيم",
    phone: "01012145879",
  },

  // طبيبات النساء والتوليد
  {
    id: "doc_fgyn_1",
    name: "دكتورة/ أماني يونس",
    specialty: "طبيبات النساء والتوليد",
    specialtyId: "female_gynecology",
    address: "ش السلام",
    phone: "01152177705",
  },
  {
    id: "doc_fgyn_2",
    name: "دكتورة/ أم هاشم الجمال",
    specialty: "طبيبات النساء والتوليد",
    specialtyId: "female_gynecology",
    address: "ش طه حسين",
    phone: "01117174519",
  },
  {
    id: "doc_fgyn_3",
    name: "دكتورة/ بطة الجهمي",
    specialty: "طبيبات النساء والتوليد",
    specialtyId: "female_gynecology",
    address: "ش السلام",
    phone: "01228592336",
  },
  {
    id: "doc_fgyn_4",
    name: "دكتورة/ سوسن أبو السعود",
    specialty: "طبيبات النساء والتوليد",
    specialtyId: "female_gynecology",
    address: "ش المحطة",
    phone: "3552606",
  },
  {
    id: "doc_fgyn_5",
    name: "دكتورة/ شيماء محمد حسين",
    specialty: "طبيبات النساء والتوليد",
    specialtyId: "female_gynecology",
    address: "ش طه حسين",
    phone: "01119174772",
  },
  {
    id: "doc_fgyn_6",
    name: "دكتورة/ علا أبو سريع",
    specialty: "طبيبات النساء والتوليد",
    specialtyId: "female_gynecology",
    address: "ش الكوبري الجديد",
    phone: "3551843",
  },
  {
    id: "doc_fgyn_7",
    name: "دكتورة/ فاطمة مظهر",
    specialty: "طبيبات النساء والتوليد",
    specialtyId: "female_gynecology",
    address: "ش التأمينات",
    phone: "01119277930",
  },
  {
    id: "doc_fgyn_8",
    name: "دكتورة/ مروة ممدوح",
    specialty: "طبيبات النساء والتوليد",
    specialtyId: "female_gynecology",
    address: "ش طه حسين",
    phone: "01211922217",
  },
  {
    id: "doc_fgyn_9",
    name: "دكتورة/ نهى لبيب",
    specialty: "طبيبات النساء والتوليد",
    specialtyId: "female_gynecology",
    address: "ش أسواق الاتحاد",
    phone: "—",
  },
  {
    id: "doc_fgyn_10",
    name: "دكتورة/ نورا الجهمي",
    specialty: "طبيبات النساء والتوليد",
    specialtyId: "female_gynecology",
    address: "ش طه حسين",
    phone: "3557007",
  },
  {
    id: "doc_fgyn_11",
    name: "دكتورة/ هبه محمد عبد الوهاب",
    specialty: "طبيبات النساء والتوليد",
    specialtyId: "female_gynecology",
    address: "ش أدهم البحري",
    phone: "01060980656",
  },

  // معامل التحاليل
  {
    id: "doc_lab_1",
    name: "دكتور/ حسين علي حسين – معمل الحسيني",
    specialty: "معامل التحاليل",
    specialtyId: "labs",
    address: "أول ش طه حسين – الفرع الجديد: ش السلام ناصية الإنجيلية",
    phone: "01006592488",
  },
  {
    id: "doc_lab_2",
    name: "معمل البرج",
    specialty: "معامل التحاليل",
    specialtyId: "labs",
    address: "8 ش الجمهورية – الدور الثاني",
    phone: "01117773029 / 0863567954 / 0863567953",
  },
  {
    id: "doc_lab_3",
    name: "معامل البحوث للتحاليل الطبية – دكتور/ فادي صبري كامل",
    specialty: "معامل التحاليل",
    specialtyId: "labs",
    address: "ش أسواق حبيبة – أعلى صيدلية السنترال",
    phone: "01020374054",
  },
];

export function isRestaurantOpen(workingHours) {
  if (!workingHours || !workingHours.start || !workingHours.end) {
    return true;
  }
  try {
    const now = new Date();
    const currentHour = now.getHours();
    const currentMinute = now.getMinutes();
    const currentTimeInMinutes = currentHour * 60 + currentMinute;

    const parseTimeToMinutes = (timeStr) => {
      if (!timeStr) return 0;
      const [hours, minutes] = timeStr.split(":").map(Number);
      return hours * 60 + (minutes || 0);
    };

    const startMinutes = parseTimeToMinutes(workingHours.start);
    let endMinutes = parseTimeToMinutes(workingHours.end);

    if (endMinutes < startMinutes) {
      if (
        currentTimeInMinutes >= startMinutes ||
        currentTimeInMinutes < endMinutes
      ) {
        return true;
      }
      return false;
    } else {
      return (
        currentTimeInMinutes >= startMinutes &&
        currentTimeInMinutes <= endMinutes
      );
    }
  } catch (error) {
    console.error("Error parsing working hours:", error);
    return true;
  }
}

export function getPromoCode(restaurant) {
  if (!restaurant) return "";
  if (restaurant.promoCode) return restaurant.promoCode;

  const today = new Date();
  const dateStr = `${today.getMonth() + 1}${today.getDate()}`;

  const knownPrefixes = {
    21: "TK", // مطعم توكيو
    23: "YN", // اسماك يونس
    22: "HOU", // تيك اوي حوده
    20: "GDO", // جدو الشام
    19: "HND", // كشري هند
    18: "HYB", // هاي بروست
    17: "ARS", // مطعم عروس الشام
    16: "BBA", // بابا برجر
    11: "MZK", // مزيكا كريب
    12: "TWR", // مطعم الثورة
    14: "SHR", // كريب وبيتزا الشريعي
    8: "TLT", // مشويات أبو طلعت
    7: "ALI", // أبو علي بروست
    9: "DOC", // دكتور بوكس
    13: "SHC", // الشريعي فرايد تشيكن
    10: "KOK", // كوكب السعادة
    24: "HLB", // حلا بحليب
    25: "KFT", // رغيف كفتة
    26: "KSH", // كوشي سوشي
    27: "SHT", // مطعم شطة
  };

  let prefix = knownPrefixes[String(restaurant.id)];

  if (!prefix) {
    const englishMatch = restaurant.name.match(/[a-zA-Z]+/g);
    if (englishMatch && englishMatch.length > 0) {
      prefix = englishMatch[0].substring(0, 3).toUpperCase();
    } else {
      const cleanName = restaurant.name
        .replace(/مطعم|أسماك|كريب|بيتزا|ساندوتشات|حلواني/g, "")
        .trim();
      const words = cleanName.split(/\s+/);
      if (words.length >= 2) {
        prefix = (words[0][0] + words[1][0]).toUpperCase();
      } else if (words.length === 1 && words[0].length >= 2) {
        prefix = (words[0][0] + words[0][1]).toUpperCase();
      } else {
        prefix = "MG";
      }
    }
  }

  return `${prefix}-${dateStr}`;
}

export const INITIAL_PHARMACIES = [
  {
    id: "ph_1",
    name: "صيدليه مدنى",
    address: "شارع طه حسين",
    phone: "011 52091052",
    workingHours: "مفتوح على مدار الساعة",
    locationUrl:
      "https://www.google.com/maps/dir//%D8%B5%D9%8A%D8%AF%D9%84%D9%8A%D9%87+%D9%85%D8%AF%D9%86%D9%89%D8%8C+%D8%B4%D8%A7%D8%B1%D8%B9+%D8%B7%D9%87+%D8%AD%D8%B3%D9%8A%D9%86%D8%8C+%D9%85%D8%AF%D9%8A%D9%86%D8%A9+%D9%85%D8%BA%D8%A7%D8%BA%D8%A9%D8%8C+%D9%85%D8%B1%D9%83%D8%B2+%D9%85%D8%BA%D8%A7%D8%BA%D8%A9%D8%8C+%D9%85%D8%AD%D8%A7%D9%81%D8%B8%D8%A9+%D8%A7%D9%84%D9%85%D9%86%D9%8A%D8%A7+61691%E2%80%AD/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x145bada485437e5f:0x8b2f27f90e3ddb01?sa=X&ved=1t:57443&ictx=111",
  },
  {
    id: "ph_2",
    name: "صيدليات مدني",
    address: "تقاطع شارع صلاح الدين مع شارع عبد العظيم",
    phone: "16791",
    workingHours: "مفتوح على مدار الساعة",
    locationUrl:
      "https://www.google.com/maps/dir//%D8%B5%D9%8A%D8%AF%D9%84%D9%8A%D8%A7%D8%AA+%D9%85%D8%AF%D9%86%D9%8A16791,+sallah+el+din+street+with+abd+alazim+street,+%D9%85%D8%B1%D9%83%D8%B2+%D9%85%D8%BA%D8%A7%D8%BA%D8%A9%D8%8C+%D9%85%D8%AD%D8%A7%D9%81%D8%B8%D8%A9+%D8%A7%D9%84%D9%85%D9%86%D9%8A%D8%A7+61691%E2%80%AD/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x145bada413265735:0x4353212d9429b99c?sa=X&ved=1t:57443&ictx=111",
  },
  {
    id: "ph_3",
    name: "صيدلية د. شعبان بكير",
    address: "مدينة مغاغة",
    phone: "011 18877202",
    workingHours: "يغلق عند الساعة ١٢ ص",
    locationUrl:
      "https://www.google.com/maps/dir//JRXQ%2B5GV+%D8%B5%D9%8A%D8%AF%D9%84%D9%8A%D8%A9+%D8%AF.+%D8%B4%D8%B9%D8%A8%D8%A7%D9%86+%D8%A8%D9%83%D9%8A%D8%B1%D8%8C+%D9%85%D8%AF%D9%8A%D9%86%D8%A9+%D9%85%D8%BA%D8%A7%D8%BA%D8%A9%D8%8C+%D9%85%D8%B1%D9%83%D8%B2+%D9%85%D8%BA%D8%A7%D8%BA%D8%A9%D8%8C+%D9%85%D8%AD%D8%A7%D9%81%D8%B8%D8%A9+%D8%A7%D9%84%D9%85%D9%86%D9%8A%D8%A7+2547510%E2%80%AD/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x145bac67d65b9509:0xba7a57328575672b?sa=X&ved=1t:57443&ictx=111",
  },
  {
    id: "ph_4",
    name: "صيدليات فضل",
    address: "مغاغه شارع السلام امام قاعة الماسه بجوار مسجد السمسطاوي",
    phone: "011 49966075",
    workingHours: "مفتوح على مدار الساعة",
    locationUrl:
      "https://www.google.com/maps/dir//%D8%B5%D9%8A%D8%AF%D9%84%D9%8A%D8%A7%D8%AA+%D9%81%D8%B6%D9%84%D8%8C+%D8%B5%D9%8A%D8%AF%D9%84%D9%8A%D8%A7%D8%AA+%D9%81%D8%B6%D9%84%D8%8C+%D9%85%D8%BA%D8%A7%D8%BA%D9%87+%D8%B4%D8%A7%D8%B1%D8%B9+%D8%A7%D9%84%D8%B3%D9%84%D8%A7%D9%85+%D8%A7%D9%84%D8%B9%D8%AF%D9%88%D9%87+%D8%A7%D9%85%D8%A7%D9%85+%D8%A7%D9%84%D9%86%D8%A7%D8%AF%D9%8A+%D8%A7%D9%84%D8%B1%D9%8A%D8%A7%D8%B6%D9%8A%D8%8C+%D9%85%D8%AD%D8%A7%D9%81%D8%B8%D8%A9+%D8%A7%D9%84%D9%85%D9%86%D9%8A%D8%A7%E2%80%AD/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x145badf71f982a81:0x727647f1554e197d?sa=X&ved=1t:57443&ictx=111",
  },
  {
    id: "ph_5",
    name: "صيدلية الدكتور وليد عبد الماجد",
    address: "أطنيه، مركز مغاغة",
    phone: "0867562952 / 01113401118 / 01010971100",
    workingHours: "مفتوح على مدار الساعة",
    locationUrl:
      "https://www.google.com/maps/dir//MR3P%2B244+%D8%B5%D9%8A%D8%AF%D9%84%D9%8A%D8%A9+%D8%A7%D9%84%D8%AF%D9%83%D8%AA%D9%88%D8%B1+%D9%88%D9%84%D9%8A%D8%AF+%D8%B9%D8%A8%D8%AF+%D8%A7%D9%84%D9%85%D8%A7%D8%AC%D8%AF%D8%8C+%D8%A3%D8%B7%D9%86%D9%8A%D9%87%D8%8C+%D9%85%D8%B1%D9%83%D8%B2+%D9%85%D8%BA%D8%A7%D8%BA%D8%A9%D8%8C+%D9%85%D8%AD%D8%A7%D9%81%D8%B8%D8%A9+%D8%A7%D9%84%D9%85%D9%86%D9%8A%D8%A7+2546260%E2%80%AD/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x145bac4258bcd4d3:0x1049d0d2c42ec1c3?sa=X&ved=1t:57443&ictx=111",
  },
  {
    id: "ph_6",
    name: "صيدلية الزهور",
    address: "حي الزهور، مدينة مغاغة",
    phone: "010 32220167",
    workingHours: "يغلق عند الساعة ١١ م",
    locationUrl:
      "https://www.google.com/maps/dir//JRWR%2BHQW+%D8%B5%D9%8A%D8%AF%D9%84%D9%8A%D8%A9+%D8%A7%D9%84%D8%B2%D9%87%D9%88%D8%B1%D8%8C+%D9%85%D8%AF%D9%8A%D9%86%D8%A9+%D9%85%D8%BA%D8%A7%D8%BA%D8%A9%D8%8C+%D9%85%D8%B1%D9%83%D8%B2+%D9%85%D8%BA%D8%A7%D8%BA%D8%A9%D8%8C+%D9%85%D8%AD%D8%A7%D9%81%D8%B8%D8%A9+%D8%A7%D9%84%D9%85%D9%86%D9%8A%D8%A7+2547545%E2%80%AD/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x145badf18344d0af:0x32567d22233fd194?sa=X&ved=1t:57443&ictx=111",
  },
  {
    id: "ph_7",
    name: "صيدليه دكتور رمزي",
    address: "شارع الجمهورية، مدينة مغاغة",
    phone: "010 26108766",
    workingHours: "مفتوح",
    locationUrl:
      "https://www.google.com/maps/dir//JRXR%2BFF9+%D8%B5%D9%8A%D8%AF%D9%84%D9%8A%D9%87+%D8%AF%D9%83%D8%AA%D9%88%D8%B1+%D8%B1%D9%85%D8%B2%D9%8A%D8%8C+%D8%B4%D8%A7%D8%B1%D8%B9+%D8%A7%D9%84%D8%AC%D9%85%D9%87%D9%88%D8%B1%D9%8A%D8%A9%D8%8C+%D9%85%D8%AF%D9%8A%D9%86%D8%A9+%D9%85%D8%BA%D8%A7%D8%BA%D8%A9%D8%8C+%D9%85%D8%B1%D9%83%D8%B2+%D9%85%D8%BA%D8%A7%D8%BA%D8%A9%D8%8C+%D9%85%D8%AD%D8%A7%D9%81%D8%B8%D8%A9+%D8%A7%D9%84%D9%85%D9%86%D9%8A%D8%A7+2547541%E2%80%AD/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x145bac679d4186af:0xd1877fd779a33def?sa=X&ved=1t:57443&ictx=111",
  },
];
